Queue is fertig
KuroiX/sequencejump pull request #1
Opened 2021-04-16 14:46 UTC by Daki21

pls review code

2021-04-16 15:04 UTC, KuroiX requested changes
Needs improvement

2021-04-16 15:07 UTC, Daki21 commented on Assets/CustomQueue.cs
> +public class CustomQueue<T> : MonoBehaviour
why tho

2021-04-16 15:08 UTC, KuroiX commented on Assets/CustomQueue.cs
> +public class CustomQueue<T> : MonoBehaviour
MonoBehavior is a class provided by unity so you can attack it as a component to a GameObject. The queue however is not supposed to be attachable.

2021-04-19 10:34 UTC, Daki21 commented on Assets/CustomQueue.cs
> +public class CustomQueue<T> : MonoBehaviour
but why do you want to attack it :O

2021-04-20 01:09 UTC, KuroiX commented
I dont know how to re-review the code D:

2021-04-20 01:27 UTC, KuroiX requested changes
Good changes, i could not find any mistakes. The comments can be improved to be more descriptive.

Has the queue been tested?

2021-04-20 01:27 UTC, KuroiX commented on Assets/CustomQueue.cs
> +public class CustomQueue<T> {
Description of class is missing (same as with methods)

2021-04-20 01:27 UTC, KuroiX commented on Assets/CustomQueue.cs
> +    /// <returns>true if successful, false if not successful</returns>
Summary should answer the question "What does this method/class do?" so the answer would be in third person singular: "Queues up a T"
Also: "queue up" not coherent with "enqueue, t not very specific -> "Enqueues an item"
"this is the parameter that gets queued up" -> "Item that gets enqueued"
<returns> does not exist anymore in the new method

2021-04-20 01:27 UTC, KuroiX commented on Assets/CustomQueue.cs
> +    public void Enqueue(T value)
rename "value" to "item"

2021-04-20 01:27 UTC, KuroiX commented on Assets/CustomQueue.cs
> +    /// Dequeue a T
Dequeues the next item

2021-04-20 01:27 UTC, KuroiX commented on Assets/CustomQueue.cs
> +    /// <returns>T that got dequeued</returns>
Item that got dequeued

2021-04-20 01:27 UTC, KuroiX commented on Assets/CustomQueue.cs
> +    /// See the next T to be dequeued
answer "what does the method do?"

2021-04-20 01:27 UTC, KuroiX commented on Assets/CustomQueue.cs
> +    /// <returns>the next T to be dequeued</returns>
The

2021-04-20 01:27 UTC, KuroiX commented on Assets/CustomQueue.cs
> +    /// <returns>true if empty, false if not empty</returns>
True

2021-04-20 01:27 UTC, KuroiX commented on Assets/CustomQueue.cs
> +    /// Reset the queue
Resets the queue

2021-04-20 01:27 UTC, KuroiX commented on Assets/CustomQueue.cs
> +public class CustomQueue<T> {
Rename to "ResettableQueue" for better expressivness

2021-04-20 01:27 UTC, KuroiX commented on Assets/CustomQueue.cs
> +    public void Enqueue(T value)
keep in mind when changing the method head to also change the description, e.g. the parameter name

2021-04-20 15:25 UTC, KuroiX commented
Test

2021-05-02 14:23 UTC, KuroiX approved these changes

2021-05-02 14:23 UTC, Daki21 commented
Hey ich bin fertig

2021-05-02 14:24 UTC, merged